server:
  port: 8083
  
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: CITIZEN-SERVICE
        uri: lb://CITIZEN-SERVICE
        predicates:
        - Path=/citizens/**
          
      